### PR TITLE
Fix GIF position sticking when trying to scroll with Ctrl+scroll wheel

### LINKED ISSUE #478: Scrolling in viewport with GIF playing sticks to center of screen
**Environment:**
- OS: macOS Monterey
- qView version: 5.0

**Information:**
title

### PR DESCRIPTION
**Pull request by jdpurcell**
Fixes #478. Only happened when "Image scaling" was enabled, because that resets the transform and reapplies parts of it such as mirroring and flipping. It's not reapplying translations though, hence the bug. But we can use the scrollbars instead, to match what happens when the image is panned around by clicking and dragging in the viewport.

The other benefit of this approach is it makes the scrolling speed feel constant regardless of zoom level even if "Image scaling" is disabled, whereas before it would feel less sensitive the further the image was zoomed out.

### CODE REVIEW

File: src/qvgraphicsview.cpp [hunk 1]
```diff
@@ -167,10 +168,20 @@ void QVGraphicsView::wheelEvent(QWheelEvent *event)
...
+        if (event->modifiers() & Qt::ShiftModifier)
+            std::swap(scrollX, scrollY);
+
+        QPointF targetScrollDelta = QPointF(scrollX, scrollY) - lastScrollRoundingError;
+        QPoint roundedScrollDelta = targetScrollDelta.toPoint();
+
+        horizontalScrollBar()->setValue(horizontalScrollBar()->value() + roundedScrollDelta.x());
+        verticalScrollBar()->setValue(verticalScrollBar()->value() + roundedScrollDelta.y());
+
+        lastScrollRoundingError = roundedScrollDelta - targetScrollDelta;
```
Comment (jdpurcell) [inline src/qvgraphicsview.cpp:184]: Scrollbars use integer values so the rounding error is tracked to avoid swallowing 1 pixel angle deltas as can happen with precision touchpads. You can see the effect of this code even with a normal mouse by setting `scrollDivisor` to 240 (2 wheel ticks), which should result in 1 pixel scrolled for every other wheel tick.

**Comment by jdpurcell** [comment]
Bonus fix committed: as I was testing right-to-left layout direction (`graphicsView->setLayoutDirection(Qt::RightToLeft);`), I noticed a place where the horizontal scrollbar's reverse effect needed to be accounted for.

**Comment by jurplel** [comment]
Thank you for fixing my embarrassing novice code :p
